name: 'Automatic Tagging'
run-name: 'Automatic git version tagging'

on:
  pull_request:
    types: [closed]
    branches: [master]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  execute-script:
    # Only run if the pull request was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch "master"
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
          fetch-tags: true
          ref: 'master'
        
      - name: Execute script.sh
        id: tag_script
        run: |
          ./tag.sh >> $GITHUB_OUTPUT
      
      - name: Apply tag
        if: ${{ steps.tag_script.outputs.newtag != '' }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.tag_script.outputs.newtag }}
          tag_exists_error: false
          message: "Version ${{ steps.tag_script.outputs.newtag }}"
          